{"timestamp":"2025-06-12T16:39:04.078866","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-06-12T16:39:04.081299","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-06-12T16:39:04.304657Z","level":"error","event":"%3|1749746344.303|FAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 2ms in state CONNECT)","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-12T16:39:04.417994Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-12T16:39:04.419451Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-12T16:39:04.420256Z","level":"info","event":"Current task name:consume_from_topic","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-12T16:39:04.421267Z","level":"info","event":"Dag name:consume_kafka_msgs","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-12T16:39:04.342343","level":"info","event":"Secrets backends loaded for worker","count":1,"backend_classes":["EnvironmentVariablesBackend"],"logger":"supervisor"}
{"timestamp":"2025-06-12T16:39:04.419073","level":"info","event":"Connection Retrieved 'consumer_task'","logger":"airflow.hooks.base"}
{"timestamp":"2025-06-12T16:39:04.423799Z","level":"error","event":"%3|1749746344.423|FAIL|rdkafka#consumer-2| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-12T16:39:04.424369Z","level":"info","event":"Exception received:  KafkaError{code=_TRANSPORT,val=-195,str=\"localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT)\"}","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-12T16:39:04.424691Z","level":"info","event":"Exception received:  KafkaError{code=_ALL_BROKERS_DOWN,val=-187,str=\"1/1 brokers are down\"}","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-12T16:39:04.475674Z","level":"error","event":"%3|1749746344.475|FAIL|rdkafka#consumer-2| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-12T16:39:04.476320Z","level":"info","event":"Exception received:  KafkaError{code=_TRANSPORT,val=-195,str=\"localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)\"}","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-12T16:39:05.303887Z","level":"error","event":"%3|1749746345.300|FAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-12T16:39:34.484223Z","level":"error","event":"%3|1749746374.481|FAIL|rdkafka#consumer-2| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 567 identical error(s) suppressed)","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-12T16:39:34.490709Z","level":"info","event":"Exception received:  KafkaError{code=_TRANSPORT,val=-195,str=\"localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 567 identical error(s) suppressed)\"}","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-12T16:39:35.360208Z","level":"error","event":"%3|1749746375.359|FAIL|rdkafka#producer-1| [thrd:localhost:9092/bootstrap]: localhost:9092/bootstrap: Connect to ipv4#127.0.0.1:9092 failed: Connection refused (after 0ms in state CONNECT, 30 identical error(s) suppressed)","chan":"stderr","logger":"task"}
{"timestamp":"2025-06-12T16:40:04.431249","level":"info","event":"Reached end of log. Exiting.","logger":"airflow.task.operators.airflow.providers.apache.kafka.operators.consume.ConsumeFromTopicOperator"}
{"timestamp":"2025-06-12T16:40:04.433361","level":"info","event":"committing offset at end_of_operator","logger":"airflow.task.operators.airflow.providers.apache.kafka.operators.consume.ConsumeFromTopicOperator"}
{"timestamp":"2025-06-12T16:40:04.552381Z","level":"info","event":"Task instance in success state","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-12T16:40:04.552714Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.RUNNING","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-12T16:40:04.552847Z","level":"info","event":"Task operator:<Task(ConsumeFromTopicOperator): consume_from_topic>","chan":"stdout","logger":"task"}
